apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - namespace.yaml
  - network-policy.yaml
  - rbac.yaml
  - ingressclass.yaml
  - deployment.yaml
  - service.yaml
  # dashboard-ingress/ kustomization is only used by the prod overlay (requires a host to avoid routing conflicts).
