apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/component: alerting
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  alertmanager.yml: ENC[AES256_GCM,data:sttyqA17thLV6HE3IuO2zOy0rcwrYfUdBqLB2G/LUIijfU/JIP1op5SfQrEw7vNZnOILEURnbMd5/lVuv4V0IsyW70DrirTzIK3RfQWSx9Rh+2pO02tx3Lby6B6LOhuQPeHD0RErgJ7IkZ0EJsw1SBJWlmO44hYcEnPcJRCrwtF63W9XmTHgjlzKDn5uiSRHQhGeMgT1AFo94ISD0DcOn/JQuMShFBfxpdQStFFI3bB+SBzyGZVmNNxKrmW4sNj+gmi4fSewCvthj/1HOrD1eV+jfGbA7GFedMFm/MQ46yV77tojFsD89TZ5yel3rEtBQzUDvl7Sda4I9PAMilrd7FwHuv3qhLqL4sFp4LLrP5UOSfCepKj9yFoh+n+nJVZ+Rre/ksjW0CwK5RyQXM5B4xeoEOmPZof3jNjI0AnuFTSM4oFYbddph3i8pVgixL3tgGPDJpGDVQ==,iv:Jt5Vjt3A5Ec0o8jxMsYanqj5xcJuhIdNASh0PvRfC10=,tag:A0lmqozeHg/Y/uOPhSzMrQ==,type:str]
sops:
  age:
    - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnN2tuRUhRdC9ud3E5Yi85
        TENMZS9oR3NOR3owZVljSmNmNFdWa1VVSlJvClQvQmdVODBUbjkyNnQzbS9oZzhR
        RUhSTWVMWUVURGhiZis1b3FIZ1d6TlUKLS0tIDN1Y2s5cEVSNy9tcER1MlE1VkxO
        UHdRYlVEYXppUWgxUnNDMjZxaThQV2cKCKna2SRqpIzPWJ1a0c+/Aub3+RSst9NO
        GFfecY1Z3pmthoUSrnVRtJsPULSz18M5Ha6cMaILfEJqJbRwC/CPIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T18:46:23Z"
  mac: ENC[AES256_GCM,data:1/RgwILivobHUUz2dlOKz0os5qDxDpoCJ3XbPvDC+mumR1M+H3PAZoSNPJaamrJFlj3Sv5bs2QATRg5qWikNgx17Sk3izQ72R2/rbKs9CvoRVJP/fu5EQo/o188gXWoAswBLh0TMSyah/yz2WlCsU7bh/v6vam23ahQ2Jj4XUUg=,iv:Kf1eyrlmFBqfsvtOluvkBJv7I35bqLSbbXiQ402OICo=,tag:LpSGRY+8M3Y7HRDf7fnbqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
