apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/component: alerting
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  alertmanager.yml: ENC[AES256_GCM,data:imcrua5T581+PHrSyN+wHLmLwRElLOiYIDB5QYtJLHRaqo/0y+K+YpTpRPUJm6PMAXvAlvJGOieOyWmiGd0soC5JKPffgf0sNkEUf/HMbW3Hte2nQoiVoytrzZHnToRM7qyeMR3fBl4XdCVM88Ntd+w5yWmDVe+MdiywmusYLexExlzlzLlV41HfXNmg4xDfuRsRAInRUUg/MxdufkbNw4Y5N6D9luBlK93Uq8cib/z6u2inJpIlhZ5DrkFlQN3u+Pe2mnO2R1vt3Vg9whivvu46gQ0oxJhCj6NA3hOP6fNUmgVPP5HGoMcJi8jO/7SOzZDwmUxBPh6FLvys1Q1TmmNgqXJzNfD2bCanu7WtSEDyjoc52dYL1VbLVH/NqsrmVC4UznQYFhqw5ngCJZgbM0NKdwtwxOpEFTEbiOEXCqUSPabTciDTr9qLzxz8cWzchVqAD3z1mA==,iv:VlYzVrEhS4m5YgOq39MfP60PIOaUmZ9zaDgfoiCLWkg=,tag:3pNqimBcJPLRn5rAHHrCFQ==,type:str]
sops:
  age:
    - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSHI0bkVOYm9SRktra0g0
        bUFicnFjQkN0c3RsM2NNTGpRc2dVSXNuTVRFCllHWkRzUDVVUFc0L29CbHlKWUNQ
        eGZCMHcvOVFIclFZWUYwUnRINENaeFEKLS0tIGIvaW9zQm1HWWVPb0FZSXlBRlZL
        MlZmcjJUbmt4SFMzcVF1WmxlN2tTZVEK9e7k/t2yCLErzTO25t5tYx546LX/6fim
        gnNtbiJngbhcS3j+d0LcOLdcoZV/g34XrLx4ha1nHbs3pMg82NCtfA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T20:21:29Z"
  mac: ENC[AES256_GCM,data:S3m2fYwv5Crj760MDlgXzznk2V4ayh2ZkAZPHsgAA1TteZSVqsh9AQHs0stwEYg+ZOyqJF5EVmievJcMsXDwisLQDasB+DMicpSvIcqm0GPKET3XJkmIeoSiEQIjvRGaryHKwP8dDysnYV5d9JGusC5GtL6Wzc12V/bh9JXHEJA=,iv:r221DVCnHC06yp7Pe9kuhNMaHI+KNy+s/NMR1On71+4=,tag:rSQ2ccIW+gFRn1AaJTUECQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
