apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/component: alerting
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
    alertmanager.yml: ENC[AES256_GCM,data:37PAk0aXLYBt14C5PdkXi3mtszCxfppJMeBwB6b6xnzz/DvU5SN0UI4hqwZT+uCCAiUmQWrkkLvoV5OHqIGeCU2brcTAanjshy85+sEUHfhdlFhLZFSr6l5EaignBYiEYppomtyU2kRLzkKj8bCY9RuXNxj7WAjNOvO/9dLfNoK8jEnc4+E8wUt0ivRqr5vsUf0s8leA25RBMCzM+l04r+Z7qmnlF23pin8MMXG/URHYItm43RL1uBt1LsVcRbLsFwwZ0K2+tRWWjdkOutakVycW9eb0Ux22381hnbAikDShMXP6Sx/sjtQ4nyRi9rhLTwKjaXk84sizL7qsmWxReJPMPpWPpcggnBFwVVxemtxB38gjOEE0iM9bDtLm55innG5ofv2hzHJVHTiQZjXvThkvzkhrV5aV1HetgKBvKrg89pwVBXyZ3993lug5IIFCewCvqVursVI=,iv:ha6Izt8BAs5Khhbi4gtTAr2DkijG7+zSToGyXSjULQw=,tag:aI6NLpIrr9uglLh1vGhM8g==,type:str]
sops:
    age:
        - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVkVBdkJXUEloR1Fmbkoz
            T1BEZlhUSTRYYURGZE1tQklJOGZpdWlrWFFrCkdBV2hZRkhzQnNNa2pRSEs0L0Fm
            VngyckpaTFdTOFpxNFJIN0UzVjhQUVUKLS0tIEs0M2N3SWwvK2NRblNTNFYxOWJC
            L3ZPNXE1L0dqLytTSThvSEUwcmRTT0kKH632rI6db+M5ZOciW+l7cy9fGZ8VB9fV
            VH/dFfWOLbWdSWlGdNLaoubiMYg94eiPsh1AcC6VKa7g3D5z8DdMig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T19:54:03Z"
    mac: ENC[AES256_GCM,data:c9OUfw4t36DwZNiZV8OXnFcOtJ2uZwq/2aU5wCXcmOWDbwXRa+WpM7pbpQW7XQPCduW7txDCnj0MoHEsjvP/XEciny/WvyxQzEoXaaFDWU+UPwxG+vNFcFh4mmBZ7w9dm0MHzkAVH0kh7gBL2rMkkqZqDLYs5614As25WEwk3Rk=,iv:RtVctilax835INJp/zdX4nO/0eAAKv0aYxD2LTeEJIk=,tag:Exdm/IxOyBDJ4c+mbZTyow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
