apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
    ADMIN_USER: ENC[AES256_GCM,data:4C3qWuI=,iv:zcc/tVmvG9z96CH+Bm8C7tMwO5A+92a6wkOyiNDoS4w=,tag:89pjNSyqe9uDgOskpdZtmg==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:gVnqWMHnK1U=,iv:v4hJL0qWOJhAmgxhyNq8C4KsMZdufnvberff4og6ElM=,tag:a+KOnoCztpBdWkdcJAd5Xw==,type:str]
sops:
    age:
        - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2djJnQ2xoWFQ2Rno2LzAy
            Ui9Vb3hhdmlnWUJHMWhHK1drR3Zvb3VockFjCnM3WEFMZURmMXh3WUd6ZDhXNncx
            SUQ3L2lXd2pRL3ZYUnM0djY3L1BXZVUKLS0tIFlBYlBBbjdGZmR3N09RakgwdzFE
            VFB6UE82eDZOZkNXS01hcTA0Uys1VG8KV3R+1oIfRVGXgqC/eI2jIujaN41KxXGc
            mCXlZEPuT07gnaZlPPjsu9OY7gTrHv+6bYbw1hnCe5QtC5x9rT5zXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T20:08:49Z"
    mac: ENC[AES256_GCM,data:Z1Z6GxeQ5UJTYurgUQC0FENO9gvfexrTKx+u71OidWJRl+fBuwaoyXgyh1lPbqUePKKNztJe8EquvzIjSsscsoEllx2XuNtuwuAk6Na31bFxbXwxO5gtxvP1bxMxO6RmNM+lUERksk1dqV/mt3wQJZPZuQU9iw6Z15mqo1OGnis=,iv:vBOqEPMvThhdoz4lZNGzMBAbc+TBjc3lJICDTcrWN38=,tag:HQIz71ntI3q0bZ7MCVq+Nw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
