apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  ADMIN_USER: ENC[AES256_GCM,data:W7+HLKU=,iv:1BYjDvCvybdbwoCTMbyqrz/WENoIGKsRd6sJSqdnOEw=,tag:vfxO0Z43jhF8n5x4Ma3YOg==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:V3Wg5XTAfsE=,iv:YzOuXiy2MqtXGMXXVaLgeXjdW0uX8rp0fX1uJjN25GI=,tag:B2BbI+2UZIqssjq8RLEfvg==,type:str]
sops:
  age:
    - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBad2VjM2FWMEY0TmNTQ2Za
        K1VQazB6YXAzSDZtYTlIa3VlUDk1S2gxTENNCjYrRHNEb3VBVWJKaUd6M1VyWGpG
        c1dnem4xeDJvaEFvMVdvMEZsdSsxN0kKLS0tIC9uWUFDSWlzVVFQYi93aHBJY1lO
        a1owOEtnb1pVMjY0alRMcllYVmVtZlkKwo4bkwqTDnACfOrXpIdHy8Uhlu56g/A2
        ixhHS9bR0lfROb77oPFBnwj4d7PtI768/j9OABz7n2boqFKyhW7yNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T18:46:23Z"
  mac: ENC[AES256_GCM,data:j3z9nZYpV7j63Ofe7VOzRXmezIjZarSy31nvpfPAh04xAoqMu+C/uH4mMYQAtED+GunwbnoD9x6KZ+QHBCv7Qf96Wwvh/0XK28EEvBZ5xkhJ8wCbDg7bjKOaqxDcW32DCTqZ+B5usb5yxgPQfDYf1RFyejQt0rfqrdiSkRAvOOA=,iv:nW4sEoL3ZiuP4IOJBHjey+IZJgvPkQgjSaEQeIieFwk=,tag:uTgLchLYEYDrEl502dLIIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
