apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  ADMIN_USER: ENC[AES256_GCM,data:w7hFN4U=,iv:b0qS8lMKn91myDcZeUzxWPbghB2fSED8XFoE4AZK4iM=,tag:psrT2yFmQBgj4AfNwY9Fbw==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:GI15kVqOM3A=,iv:zUIypoAWlIDdX3vQ/1GCXZVcapQidgNcPKO2gorGjGY=,tag:DKvbB0dzBqGjBUE8KGRIyw==,type:str]
sops:
  age:
    - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdXVzdXB0MFViTDR1YjM3
        YzFpYzVjQldTeHE1Vmc0bm5iYjFVbFFTMEQ4CkJkNkdaUFZrTzRGU3NEcjIxblZF
        UzY2cHRQYld5ZjdGUTRqRUJCVENkRmMKLS0tIGJ0UHFMbEdnZFFaSFFhMU1PR1Rn
        M3JyemJ3QlJoZEhFN1NOaEcvQnBtNUkKWRQj40lot8lnnTRYAR9ZgTukE5rocDBD
        ca04vL6esMa9FsL7cD5NRl1QSCASOHADUguGlhB5xUXJ3R36thuKaw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T20:21:46Z"
  mac: ENC[AES256_GCM,data:L41rKSVbQ7KHCEorSs/IS7nNz4dUqps2oF1tE5HEeYPrZHNUisokd7+3g7K+reHczGIevk8MG1xj8iYa0eUUvtB5lo/GWrmfwTZYyrmFT+tGmfFh0GBPOoF27chb+VuM2CtZHc8RLr5Jy3rEzGmo7oNQWbuTJk3H3P4+ke3KRPQ=,iv:FKdqiPeTO/C+bCwwMKExOIQ4F3wSI3CCwBz7nsc1CBw=,tag:IKrmuOPOLYcF8g9rBNO/SQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
