apiVersion: v1
kind: Secret
metadata:
  name: todo-api-secret
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-api
    app.kubernetes.io/instance: todo-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:yR+8IWCy6ocxE3m/0XDe858Dtfo+eISCwcYh/6VVNIOB3kotey8ytsMvhF7fAKc9e4lkIa62,iv:dK1dyeEfCdcfz/GrbY/K7nq4QyNSGnzdM4mQ7VBqLGk=,tag:D7NQTGBW/UntgIfWSdTlug==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:aULVMrLmyhK5iIGlN0JPoKGtwT4ipF5UH7BEEtMXswjex7r+bARWwVXZfCNeLnlb+6RQeRbFt7RtRVloANOR6A==,iv:mCvRdnc6PmFA6CsKnQl9iwFQEhskGpnrncYVZ6eqQ3c=,tag:QzSf5wEdXYy65lElqvqVvg==,type:str]
sops:
    age:
        - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SWhiRk5XUGxRODl3b3Jy
            d0tkelNiaE1qMjZuMGh3NjBKYlhGUFJLaHhNCi9MSkdmbSthRTFCMEdQUS9yUnpq
            Q3FpUzB5YVBsQzZlSDhiREtxMmkvd2sKLS0tIDFnbUh6ZVFieXlEYVNUR21VL3E5
            OStMT0pYTURjTHNIRFVTY0xVdTB4dnMK7Y/rGUwtTvr/FB5jxYr6i1Q7Le73SV/+
            ccaNWMMEK3n8vTNl7VJJ90ZelKuOqlFvi8sqJsMPNtDbaJmzfs2E3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T20:08:49Z"
    mac: ENC[AES256_GCM,data:vaxbi1Ro0ZzKbOo7u43Eo/l2sEqed453slTEeKjMYpgbgTEWl6tJSDGf3eq6YJi475g+QzujeYQIzNDA1rWdm26zLSdmUGyJ6CwOBHVvYTXlK1UiH1RYozeztg9ckHRil4fDMrPX+4elJv3K72CruweWc7ryK3x2SIwSTcT6jjQ=,iv:N3lFIu6jp0k3lX8gv1twhtSqqXhy75LiWyvCGkm2nWk=,tag:vazobEs2QilFTRP3ZmftEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
