apiVersion: v1
kind: Secret
metadata:
  name: todo-db-secret
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-db
    app.kubernetes.io/instance: todo-db
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:FzmD90U=,iv:/Pmfz0V42wa/auEIWGfDdmhkUlDHeB1yeZFLNzOSjq0=,tag:G7LT53FbaqhVdzbEtfRimQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:x1c3701G5TA=,iv:+1f0N85M6AuZMc750MDIJ9xWHHLOciNFn6pWO/ZKfSo=,tag:JkukAwgsS3IUpsL7FRz/Dg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:1F2Zf3I=,iv:TWOrCJKCIwJUkpc55jRLUhWvYMOR70Ty8IGpU+SD7eM=,tag:V1NYQl1O6Z5UJvbt3MK/dg==,type:str]
sops:
    age:
        - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUW8vSWJsZDVWK0hVa2tr
            aThnMzZzYjJkSjdNejlVQTlYaW5KQytCR2k4CkVUYWVCNzhUZ28wcE85Njd2R3Ny
            QitvTzlOZXFscjhIakJSTDRQSU1oZDAKLS0tIEJEZDJoMnVpZzgxK0ROc1FGalBW
            Y0RmUEoyUjlyT2U1SEJEYlJ5ZmlrdEUKh60ZuBe+op6bXbpTfBnkxeqi2J/MsSYS
            C9UQ8O3c4tICi9XxbHbnEpaQfcN8vRsnW/cnrg3Yeo2lKokXfAmwlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T20:08:49Z"
    mac: ENC[AES256_GCM,data:42X7sAvxohP7+k04rYN32NVKb5/ADTbakZZrw1kTbljWKTFQBChKoXC0hKl8pmAjLBe9PVdh77kGiPTPUCAQvLoWKxJBuY/ykpjkwtakNX3zR+y5u6i5G7QT7Hx3WWsdXaLJbnnRZpWLaRBlj8hlBbD81pOGLCLD7sNPkZaX3Yc=,iv:QpJI4fPtFHjgBKsmvOrqRMd1ipSBb66L+S1Y6oWTy8g=,tag:3Dn3BXT36/n4dzaxh6NvSA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
