apiVersion: v1
kind: Secret
metadata:
  name: todo-api-secret
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-api
    app.kubernetes.io/instance: todo-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:Ms0phyml6MnUFSwHAV2V0mE8d8Zuxm6VFMvKS+bZvs1ZgR/G5W+OETzUwePhL11w7wuheO7p,iv:xquKbMqQepDvS6/I0X/cp6HGY2hPZxJXPDnVqxJb3xc=,tag:vHcvX6oXCXykiDxGzIhK/g==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:2+GzaOvXFeD0lmORRoJe4dSPBgf3Vi2rvh7GPUGXTdNAwrQy+Tq+tohmjTI6joC6C/3ZLN/pCNM+vYaS19MStQ==,iv:eOIsV2xLJtwDq+SMwmcv6GrvwZT1u0Svnv6U63897is=,tag:PVvolqHmJ4fhgp2i8xw1eg==,type:str]
sops:
  age:
    - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYXFnSExvVUYyY002bUZL
        OVZPSkt2ZC82QjRBZG1qRHgzMTJzS3RzcXo4CmRJR3E4S0tld2dOb0NPS0djdUQv
        YlVPbzhValZxSGlLeDFlTmVQemUzKzQKLS0tIGp2NzVDeXl6STdXWkYxMWdHclE1
        THFmRDVJY0tUclJoWTNCM2tQeFhCbWsKE/+cNNR3o9YCirjAPYzLKCfDDezA8kiH
        CIo7aWWYnvZWEdBAGvFQyRN6cU/mSuIS3RKlMNp6qGh+ciuSqefD7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T18:46:23Z"
  mac: ENC[AES256_GCM,data:YeVvILN6OXlZfRSSHk8WeWpPTbRRZjX0kHzjLBeXPKKIZ8gzkaEEHZ+V6mQgjqwhAwJjQX2H5vy8KTtzYpRwpWKbBTkmPoxAoROgiQv9vCtFK89Au+noWtfw1r+gSa7981mycsTIfwBNCQPTmvUGjE3HZycKpCjo34IHV7LSz+c=,iv:TPTkeNl639Ynu1uvyaYefGYwgclr+UPkwxGob7iML0s=,tag:qNheKoWuFPsAPX3GcOUEMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
