apiVersion: v1
kind: Secret
metadata:
  name: todo-db-secret
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-db
    app.kubernetes.io/instance: todo-db
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  POSTGRES_USER: ENC[AES256_GCM,data:zCOlh6Q=,iv:lehYHJM9JHnKK7geBWe+VjoCw1gNHp0mma/pxmGlcE0=,tag:Dbaqf2tfO9xWZRXzqAgDZA==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:BKdKJF5MD9Y=,iv:XKIJtlYfoyx0QYFgjrhgveq8PdeHngjb9sWtkywEW4Q=,tag:f0asj7w9r+QOmKgCKMnHTg==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:RpD+WKM=,iv:dtXSzwOC+sCdQW619jmMc4RA9fhLdtARBluLbtogvuk=,tag:owAjmSs0Q/fpbl7flWFHjA==,type:str]
sops:
  age:
    - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVWh1alkxdTkxNjNEQVFB
        VG9ndS9waGhmM3R4ZG5ONGwwaE9HaXZ5bFc4CjdBckJ3d21LUDYzRDdFVCt5c0pQ
        dGFOcmlXeVhPV1pxTjVZcll2ZS9iS0EKLS0tIFM2Nmp6QjVFM2ZJMGtvcm1LMUJY
        TENDOEpid1NScHl0TkJ1TWxWTXd0QmcKx7Cu0wr9CaDprvNuhPcyjgecroKPf8ND
        LmnaPty4DZnaTq+oCtc71l34cTDCTFgXQCsgVfQRLa/lERswmIqUJQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T18:46:23Z"
  mac: ENC[AES256_GCM,data:J9LQ8g6P7kUCh/rVYgqjc9+zKAwuN5RjblNvsdUBZCGN2FugFiSXqZK0EQfPB0rp/10c/ldwsIMo1OevMV3ujr+Lpf+QTQfBJ183VxDgu6XNRNt4TnLfvpskBYQKBRBRMXbG1mB/3/3OkVjqf/TUv731XuGoTSuaz6VaY6Vqy54=,iv:PPy1dvMxeIUzR29lIzigZ3tUuzPzw7TRt1mp1Km9UrA=,tag:hhy0OpUP8uZZeyept25aHw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
