apiVersion: v1
kind: Secret
metadata:
  name: todo-api-secret
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-api
    app.kubernetes.io/instance: todo-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:j1gYKG2cUyg+FR7Spy7KAdHH6Ck0E/qShVPAnbteW1274mHYey881f4KD/1+jQqleQ7H4loU5zZ4Tgkz1A/sqUYI8TIjS2pkrBqqwOiwhGGIlpkb,iv:lX31BYnWimzIsOzuXukTUHX3NbW4OnvGHI6GteRL+lE=,tag:8LfESyNREZXigIwGjwfUvg==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:YTH3HrzE+GpzVdc/ytYgntYuvl3Nc1zy4GKnmKSGjiUjfowW4UaM6jvcd08RLc8ruGOA4SgBq0rt/8m+4hF2MQ==,iv:oR/RZ+kvEPpYaSP6u9B3yxSuvOWhoUDJwqdAmRpGz04=,tag:zEaNc92FaHMyXfBvZo0WCw==,type:str]
sops:
  age:
    - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZjRCbW1lWkRIZERaN0hn
        RCs4cFFzNlNRQTJCQmJDYWZHSkZxL1UyNGpzCk1LZk1DZWdNSWd3dDdweTQ0ZWVT
        ZUt2d3RNdjQ4bW5iN3pwSDBmNE5jdTgKLS0tIElkSzIrWkpBMHprdXlVNzVyUHNR
        YVBtUHI3UEZLZ29xV2lSRG1sdG13cmsKFza1icSanObPw18rg7YC0HeuRI5oTZpE
        0bhhYoI0CW9+K1MLzooipbiTDjWqvEvuQxI4xSpbLuewCgRkNRay3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T20:22:11Z"
  mac: ENC[AES256_GCM,data:a84yKv9CLMS2OU1l2KGwVPYzObimdu3gL1PjEQ3H/W+hmM4u0gaUtBjuhc2kWcaHmAdhk9qdPi2Hnc/+1HkmJa0IvmLRCFSV1ev9KROHvtFE1ctCdtf3sam3Z8JXx5qJ2YJZsWDZ9g0pTR25hRLxPDkdUV47p0rkpG4d7ExsLjk=,iv:825EkFM5DXbPjpxXhaPAlyW7rFFVzpsreJ6SC6Am3BU=,tag:o5LR1MTmYmAP/RL6dTJIWQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
