apiVersion: v1
kind: Secret
metadata:
  name: todo-db-secret
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-db
    app.kubernetes.io/instance: todo-db
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:buwr334=,iv:WqmXNKFqMAaWI0EFqoH2tGW9OX88Kk+G1W9yP8C3mZk=,tag:rP/xWTsCz7lKMx0fRz9c4A==,type:str]
  password: ENC[AES256_GCM,data:k3jEkv0LqYc=,iv:JuowG6GVd2kWadEFKoNe3jlYJ9l9ur7mGAGCyL+fQ7M=,tag:im/RK7yvI90RFRXbfHucxA==,type:str]
sops:
  age:
    - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMnVVV2szZ0E1Y0RXbXZw
        aEIxeFJvMFhSMkRqRDIyMTBHdE9rMVI3UHlJCklOTGtvNG50TUJsNnc0Q09EcTJO
        V1MrS0tRdk01bE1nZXBVVWZjNFE2OEUKLS0tIGdYZEpqZ0RuVGFzeXNRZFhoZmwy
        bVVWSjdMSWViRGVGUjNzTVpXRVFzUW8KkkZH86qXdDM2ShOB8WygAAivZI9YqK8w
        T9L42rudtovojWrVlmYHr0JltAY10OgCju6f8SBDjFuZvNXDI8CRfw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T20:21:57Z"
  mac: ENC[AES256_GCM,data:0ZRvH7nj2EyuUHlPt6yDrc4AtiGC9605NEc/QI2jRE0E8aPGCahEAsRwv2GkaaQUffen3fqpcmSZO3WttMI20MO1zkY27bjkhlIfl8tRdfB7GnKDXiqMAgANdT9Rj2XzJWU2DVwtp4P2aXPU/ZgcHohIhuug8bhr2DlFWyLrPCc=,iv:ywv+Wa7rALiD/UJqY4eXl28Z2tLFV+ZNDSnZav7Aaeg=,tag:RA0F+xe2LD3u0cRHce0tog==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
