apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/component: alerting
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
    alertmanager.yml: ENC[AES256_GCM,data:QjJwWvkp9jebkl9raodPTH60rod9XLi3EjF5qDnmbfRUkT1pK796+gOESwvKmxDvY1JjoNRAaVnl+Ef4xlj7NHl2kPy6PXh/Ycn6gMWPuSsdhi44yXCVbCjyVbhUijHmd82lLShM0FuDF5A1j2F0TZUXOIUM97qrruQ67RyNCNr+PzPy/jlxQuojk7E0mAq/nojL3eRBbC0Rgq1+B3FhmALPaZo5F365uqL8kKVtb1H2MbhZ7tlhkmgrW8WzHGtuHxGRfn0AqZAu3qDGpR+0zTCSYvIWojhjhI4t1o0UOTNm5m4e1L/5UP6xdgoLXcxdyQBaJpHT8y2Towis2Vb8fZS+cR+QR8kqtVvcVcp3xVYHF3GBxTv2JTL6xRO9ndix1IPEBrwO4V1vU3kHpX8OxUduo6cXtMWEAN7g54YxvirEBvtm9DsDXTaG8++VbU3oUsf8qt4cKQk=,iv:H8fRnErO07d+jH09vP8vAW5FcKAqEN94e7pbYGETjAM=,tag:pK70yTP4Fc7AMv2owG7/6g==,type:str]
sops:
    age:
        - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Q2xST0ZORlJOQ2xJMFhH
            eXRGU0VSdVJrdVlYeWpqdEVGTC9rbmNlT2pvCndVVTV6YXRtK1FIU0c1QUM0eWNl
            VDFkYWNhS1g3RnN3K21SV29zODJyL2cKLS0tIHoxOHVBMjdCeVFZdExva3NxcGtI
            Ni9UMUFrTGNFaVlpTVExbm05M1VVMHcKSkCQx/XG39lHMGkd/u81GDQo1aVh86sp
            gjFGCHnol4eHWU+rxbO/7wF+d2bEgTyS0zLwlLWpSY3ZCy0NyzcjBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T19:54:03Z"
    mac: ENC[AES256_GCM,data:mqpBRds7uDwLvXoflTxnXYUClqqs3aUJ54qj9ienHKf65N7VOGDiB4JYpML1YKBVhDZQoD0jHt7xuF5Umhyundrx6wuP1QHtv0jLm+/WThVQdwC3kRzLRqTFjaxVn3Y51k9AHVk1igVHbuw1mAwzC8NHX63TEmStviXYAUvgiXY=,iv:pO0SVtjSdqohEfd6F7uTMvtTeciHmJNYN4ZxjK/ITfE=,tag:/qc0ZwKP8j6hVa75rNa3tA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
