apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/component: alerting
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  alertmanager.yml: ENC[AES256_GCM,data:Q+AZyFjv3zL2d32zF7FQybvLCwuJdRUFydxuQpr5S1Xn34EMB4GQhnGXII9eiirS0PRYAf+Lw0Jh25T9q50JV779NmkHkBwji4lX0TvBu3G0YQsKmV9T1oRIsteixPpzbnvEhdoAYNOHtfErgdYGCryrUakBqD5PLAkoPPXRLv1M9UuW9BJZehZ553rVxAhd0rU6ZW6AVGCEgAT8RuqdahJpSwnCShrQEAcWfG/RWeCwUzcDUvimJ2S2x+MEVaeFY4yQm8zDcvHHMFkzUaNGoh5gSH97tEzKCOFgUSedeFzOYlxOiBpQAW6Pm/utmiewp6l6sOkO4TLJAKoUBLqJAWo+UibmVRTzmmeta05aEgPQDEicySqheioXSY/GEV4se0u+ZgnqwjRvTQAjLbROGsHaqJup5MCKLM+4jOkr+zn9zdFXeEMN2qQpl/rsmu96/O+cd8H1dQ==,iv:MJpDR+PzV4+joEh6EM5lE+QO6uTLA4oGGMxgT4g6tk0=,tag:t5ZEUo9coiHUsZEK8p1JNg==,type:str]
sops:
  age:
    - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4LzVHa2JyZUJXWFE1Nnl5
        UDZKMVpvZ2E4ZkNybzB2dG10c1lmQ0xiTGxRCmRIRWJTdUYxcDNUNkdCQnRSTlMr
        S2VBNmFiMHJaTnJ1MXliNmNJZ3pvb28KLS0tIEVZc3pScUdGajRIVlpZU0poL1BD
        dmRNMEgrQ0prQUZLV0VFaVNwRW1BSE0KJlNIVZss9y47JbZ4Ica0BtbE3CH2jjmd
        PfRSkFwuRlsOEEAzkJZ/Npsa4GuLYnDTNOkxowWO2xfKFK9yTpMiJw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T20:21:00Z"
  mac: ENC[AES256_GCM,data:xeEZoXd+wMnCm2m3CL2DS0eiaN5YmgcfS+PH2KnYUn/tE8goMWLa+BFs46FXWo0A8z2NXtB0lF2cf7i5Mefu0uGgC+0+ZjQZmUlAdjdjhblrX0gzPBqW19S/QM6aJPcZNt2KrcwbrbLvxGwqisT0yQLmMVsj7KwctUUKPDe/M8Y=,iv:i69nkgeAWSXwjwrmu2flUsu4JxPZO7lJBngIdHIPtmk=,tag:Lg/E3Ax8UftD2KUAz/YVUQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
