apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/component: alerting
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  alertmanager.yml: ENC[AES256_GCM,data:dD0FNe3RsYjpTCKxWIgufiNJV9We3QdlB2HQQnX4jKnViZ0t/XgblRgROxjUF5qtq/arELNMhiO71D5A5ATtNWK8V09YlJFQ/gP2Ws1JjdMxi2izzi61Ovt3PI6kfth3uGTfQTWK6K1Ja0k8ASO3+gtXirNsr19DddrvrEQOKIF1OBEGIgP8L2lLPBPr55ZgYhYFRusYJR7H50tz0F6mTnF4sbUSxdF9IPlATUFwO6j15ed3XVVk2FTJJptZpi7LXxVXKOGLAKfAwYFKw8AJ7ZLpa09i3GXfKa/j0C6aKXd7E45lUNHFYDFEW8MBDzzg91x4pXRwUt+V69HAk6BmaWwrUH5BrpJD71NI/Y/ppb553d/3UG+lkKCFOch5dEqxrf5q19UmMiKmLTu/PSAESfwg/7KZnf73jBPN06AUk+qSNNo5cBXeV/RDGWjm4+rz/F6ahMHf1w==,iv:3u24BLauv8DVNENTdOpMzquF8rPdh8JFLvqpuFbG5mo=,tag:OKCUhJkcOz5s/CXMe4ZTLA==,type:str]
sops:
  age:
    - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaGdoV3YvUFRpZndZSWtK
        aG5SN3VuWlE1ZEVDSmM2RUEyc1g2NHJqTGxnClF4dXRMN3pXTmMrYmd3Q3Z6SHNy
        UFdWTjVrTGRRZ1FzSWNLY1RURXlZSTQKLS0tIFFCVStjWEYydzhOcmZLVmtObWIy
        cDduY1Z5enlmaW5CaldwL1JyN3doSFUK/gDXkKfLguV2v0dAXzFWM6zxseTNLs9B
        bC8anA3iNX7yWH2arTpCJ/N2Z+wWsEiCYKcTXJ34+PyY6qr39mAULg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T18:46:23Z"
  mac: ENC[AES256_GCM,data:DPjRsFwxLdYv4rpM81Q6UvhDU6w2DjQrTMXijrs6LuBrFHVjPQxXdBSdp75szWsnFuU5zCrNKPDcZEcdkz/PWXKMW3VLO8Bq0HEwjBqTdbSpVjaM+EGX3a1duDuN14QQ1hZ7/8PU8dp6Phu/Lag9X6+lSnOw3iLl5sr5z/YrSa4=,iv:lOzbb8pi1LbnVGei4vB+bePnvPUZYpRRJFcBiFcD4OQ=,tag:d5QfQNHg3SR61mHsKJFMzQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
