apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  ADMIN_USER: ENC[AES256_GCM,data:I41jbps=,iv:s2F38Lv/P95zxeOqyC/mFlpdKT8j/iXdJRmwNZL4Htk=,tag:gTRdCUHK1QqxVefrZ1qGSg==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:PRuFzfBus7U=,iv:1Cn9hDPbR1iWCVyMMVtetIbcR/WytPg2UoaiEpArGmY=,tag:JYRxCz5brphX2Eb/LHaCng==,type:str]
sops:
  age:
    - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZjAwL2FPNGN1TzBnOGgz
        WjFYdDdIckt1RHArRzRIL2M3SmFmNHBLclVBCi9oazY0dXMzdzVnU0s3VkxJbkxr
        M0ZFQzl0b2VqWlZtYnQxNy9zcERZb0EKLS0tIGN5WStwczRJaWlldGo5cjlYR0s1
        S29HcktBQktzR084VXllMDlEK2xkTW8KDR1QAjSq+FdE5oSKqetZXL+2SKPAnOMf
        lOCXh4ojkQkxO9QyfruPKmhct+zN7xAkBJ0OpwWKYH/IcsyBDtjqYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T18:46:23Z"
  mac: ENC[AES256_GCM,data:yfGypDcVAr5Lr6O40N1/Kqq4xc0iv1GfEsLM/rUJ57rgoN66AxlC7UoTMBjdGURE/t6T/3KjyzRKktTx6+deNLho96qNeN2o/o2U4pDUvYBOjMwP6BtgFamBDyL7aH8AiKS5zXD5Ssk1vd7Qq1DSHDhjqMtg0Ts2qxoqnvTRsgY=,iv:ICm5ZqEvPB5tNr5Wb7F/hiVqFcgyn2jDbjpA4BJT1tc=,tag:yCZZ8I5EoFvK61o5rcu2OQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
