apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
    ADMIN_USER: ENC[AES256_GCM,data:L9+9yb4=,iv:fv0lmzdXFvESvZymae9CfH15NHvTlRxbtN8gHcPww+I=,tag:gpLuzwwnS86fHj64DxfQbw==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:1HRtN0sdCl4=,iv:qKOKq8kKaUm7BvlGuoujtsdTSN46bhv+hEtATNNdZho=,tag:2d4yGO2qLs75oljUKdKIvg==,type:str]
sops:
    age:
        - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFb1FNYzYwVGQ2SzkvQUs4
            VmhTakQ3ZnlaRHFHcEYzMkl0LzZuMEZnUHhZCkU1U3BVOEJYd1BjYTJHbXJQZXZT
            aWt5c3ZtODIrNGFiUGRmemNuUXlRNTAKLS0tIHgwK0lBOC9jVVlCanhOK2diUWIr
            S2h4dVA3VUJRZ29GazNXV2J5ckplcTQKM3W+D9b0fL/nG+eNHOTd/TIVyhFcIqRM
            m235ey20Ux+5hG3WkXa32Ya7Jwlz6GbHfQLYUV380b6ArmeVg1miMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T20:08:49Z"
    mac: ENC[AES256_GCM,data:y+jJUOfaWRk5P1fHljl4sRzBjsrc3x1qraVsQqWExeI72My2XB2TTArw04WjkMh8c1g0lV9yUk7bckMslnkLiPLgfIfSEy6c8SuCiJvjUCf9Af33vyUlRzCuoYnBGWCKJSdglhzRVgCLIGObAtEZoOiSrvxxgGGJu1FUCzThN8U=,iv:Y9zCunQyX1cU6JN908MxV+1ZFdnrk99vzbGeRF6B7jg=,tag:CbQOtLP73l24XQGjALK4/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
