apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  ADMIN_USER: ENC[AES256_GCM,data:snJKr5k=,iv:hR7uLKmy+uk2nE5nF2SCMyTIIyeVEbusrwVC1sk0CKc=,tag:0TVSmQBfZDRq1ENDHoig8g==,type:str]
  ADMIN_PASSWORD: ENC[AES256_GCM,data:V8j4Kockdi0=,iv:1VWaYFdDxH8DkdGfD+DbfYIxP4OBHcmofX4vBncgbs4=,tag:CPMOOTYUPFznI11q1EnUpQ==,type:str]
sops:
  age:
    - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrejNiUzlRUGo0N2NHMHpw
        ZGNlMUovSFhmTmVKNzFFMTZPQXVDV3pFc0I0CmdSQmhYOXBrb1BtYXhsSzVhaSt5
        STQySVV5S1FHY2EyeVplK0pKdVRQTjAKLS0tIEV4NlNQZzROamhUVmNaMk5QREJJ
        c1BkR2xqcUU2V1NwTWdON1VhQmhXVFEKuGy/9ZyoHLzYiEVODwOiH2B1Ur6SB15d
        2ujvBlruk8uudo3KDlfxzk1xmg18iuLIeeRAdWD271etO7PbLdkr3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T20:21:11Z"
  mac: ENC[AES256_GCM,data:quEMwwprV6nAiVZotq4+LhlY6Bd+FTlM06mkMv9mojAR7CEYHPxla+ZDvHwzg31UUygzMMXQxt/hGb14FIL5rWUl9ZNqGfEplZVRTtgDBqyxj+JQL0gqUxyJH0eSzkdATBF1Dv9xL4YD1m/0cXY2Ima87VUYE9cv+j+Z96J4vnY=,iv:/RPfEQcCkxXBbtjWIEVWvixavcKV0Td6ujVJz04g4aA=,tag:AGzj+0oU/rfzUOOUR0XZDA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
