apiVersion: v1
kind: Secret
metadata:
  name: todo-db-secret
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-db
    app.kubernetes.io/instance: todo-db
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:9i4PT4E=,iv:pvJa2fWHs40GYChmCndL6rBSJ9o3TURd+dS4lFszTaQ=,tag:V60xPch6OevicJqiUweilA==,type:str]
  password: ENC[AES256_GCM,data:hyKWhIGNwp0=,iv:KzPaQDGQ3/BMQidY2hKR3qBO9nmf9vJ/tdKEgf/WHBk=,tag:HNL5rAevTScgBE9vHtWYkw==,type:str]
sops:
  age:
    - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZThBT3A3UTZsd1VnMU9q
        b0RhOUEwSFJKZEtmUEplSW94Q0t3c3RuNHlRCkxkb3h1MHVkYlBxQmZES05FVkV3
        YWwweTFUMitRWCt3STdDVUd4L0hTeU0KLS0tIGRzMUNSdzdXYUY1Z3lRVVFFSzlM
        Z3NBclNocWJabnB2TlN1dGZQTldSeVUKVph0bAarZuZCxKfFUZSGQKBHCHE0lh/c
        Sl1TmZRS/NJbJjz0dJGN69YIIVz8edKF3Ft/yXEQiR9mtlkOZ6vqHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T20:20:25Z"
  mac: ENC[AES256_GCM,data:l6ylbcSo+ETW5x2yZ/9neVFohZmJZ+G7UUbXk6mnpUol2hlb8swMXlkkUC1vNd6e8yO4mig9uUGst+oKYMY5PfN/DLF4IVRUiwF3ILbyU/tzNmZELE5UO2Fddx1JFj0P3h8t6tudFWl3AIZPmOAL1w2ZYqxQWWjX7eaT4FgjLps=,iv:z0r19JOfEaRdxKIVEb0hxsrQb+hQH9aPly3TGMIa6as=,tag:ha/tzsa6HEZKGllV3ufk9g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
