apiVersion: v1
kind: Secret
metadata:
  name: todo-db-secret
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-db
    app.kubernetes.io/instance: todo-db
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  POSTGRES_USER: ENC[AES256_GCM,data:d8aLHYU=,iv:ZI/ieE3+zsGk3bCWG+ZNqlzX+d8zZtx0HCZoHkHrCFE=,tag:CyYaHDaWtSwlg1G3mSE+UQ==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:xOfzHx1kq7w=,iv:l5FV8nucQHkpmIoHhBpNP9SNI1nlXiScaxphgH1KyvM=,tag:Rn2ZuqYNQpIaeYh/mynekg==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:JMf/oOA=,iv:giXgf20qLs4stmIdJJak67fIc1czTn+PFhOis2jaY/4=,tag:tdmThxyz2ofzj/T1qJTDOw==,type:str]
sops:
  age:
    - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieFcyalc5bElLQmJCNjZi
        ckYyYVNMVzVwSk1VdGM5UEEyUmxwaytKOUNBCjB2eWhyN0JMTW8wMnl5bVFnbXhw
        WGgrODB5U3NwYnNPZEloMExPODFZNFEKLS0tIDFtOW8vMUtJVXA5Q2ViTXk0dG1t
        eFdqTGlZV3dJZTNGWjlrTEJnUHJ6MTAKl+uHkhAg32vB39TE29U0qFPnSgKo8a9o
        46e39wQLXCwVEjblleHGpE5jwq3of2UgWk89xBjaE3n+qy30Dt71vQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T18:46:23Z"
  mac: ENC[AES256_GCM,data:qnrzrE9NSAU5yZTc/sUOtFmMWmE6JPDb4YQrheflQ9xNNZiRh+ChSGzRdhHdDB0BWA6nsEKf/3jChprqf1oabtncPL49ZyrJSYU7aiVRRz0Cw9tdx1VYoFmXLD/loU87mmVCm8MEihxPCP2IFOiCSFy5Luu/K+J/7H0virPZxJU=,iv:KmA4Gf8s1whxVpYL3XDOww9eqLpJH2JzMNtcR+ADsAQ=,tag:bwogC0dUBpPDbuzdUy9tLg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
