apiVersion: v1
kind: Secret
metadata:
  name: todo-api-secret
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-api
    app.kubernetes.io/instance: todo-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:5V7VX22fOmoXgmMzgAF1Jc4awc8JptkFMFlNvpKo01HdFi0alaH8p1EWnn15+oectnMYyo7x,iv:9kE5pCDaRqZMS2UFq+fNWdaK89sS6qaDHcS+r7tXszw=,tag:IG9qqAtIwOcv0GOutsO00A==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:eld6afYmVQVT+nIrDk/iYY62i0u/DR6JLFbQItwdi7o02rrzyzivtLigyWZk9oz3zfxyfnKJZQUmGKM8pUmexg==,iv:p3nabCcf9O0X4L46RP5NLelvbAdeC69g/Uzv1eA6j80=,tag:O88Hoj0lIajOkv8it7cfJg==,type:str]
sops:
    age:
        - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnb0ZoRERhTmJ2T2ZOdnlZ
            SS9nRFNUNXNCTlZtSlNaYzhySWp2azl1Z3pJCmJsQzlkU2FSKzdROTBNOWN5Zk9h
            Ry9TS1Jqd3pWbklEWVdvOVNTT0JZUEkKLS0tIHYxdFVUUzJmV1F3RnpmMmQzeDZx
            dno2UDNrMXQvbHpEWjFZVzdablVkQlkKheVi5d8CViFZhckXsMS63XLoAcnXYx9D
            dH9umH43LROkW0M7rVphZVZ9j0yOT8cUKtazomlESfxnROdRBpjoJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T20:08:49Z"
    mac: ENC[AES256_GCM,data:IychPexoccR5zjjAZbBoNmroRr/hHYjEitwYA52W+qvzgWc1Ags185a0GdmAsyL7/B9XEb49l9Yeocw98v49bAYE3t1Ikjl9uc4mRUHephw1WkXmqHwM5V7fvSVIuNj4r7EfoNVtslku6UFYG/ycm6+K42h0a7MpfqZocVADcto=,iv:D4ngKoSGaFsL89rEWlrnlHaIvPX5cIqeZ/U4Ew9AqPc=,tag:FIHkWBrhs+dA5gVblshDZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
