apiVersion: v1
kind: Secret
metadata:
  name: todo-api-secret
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-api
    app.kubernetes.io/instance: todo-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:79ryDRWmnjF0MfLs5bL5O9ba/lCJ+avy+KZJBc+dAxgtpgtX02JxqVBoniaTZeonIo79IdCjxNp+2dPGp3+N9NERg0/HihRWxKctYb7tfMSBtCm/,iv:KsB+RB2llw/8OkkZ17znKtO1pqXxVnvDKFCQttS5rUA=,tag:2E5OTteNC34KqCe04gS0OQ==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:HTziMuK0piM5/smKHKmtJfehIYwpwaPvnq7BMuisVg6kLwOtLnSvLoa6LtTuZSDeUg0wI00wc6n613hId7vi1A==,iv:zoDkb1evrxLz2bttIcOoDV+tTaPF0b+B2EtMaDsGhc0=,tag:wSGGJMqGuiVRNrBK+y74mw==,type:str]
sops:
  age:
    - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NjFDa1lCWGJFWldmajRG
        TTI3VExNQ3c1ZU9GZ0NvK3FTVHhMOVBkQlN3ClpsSnN0UE52T25pYktQVmt1VVIv
        VU5Ld2FRQ01vc01YTEIyeHB1WkgzMWcKLS0tIEQ5YlhyaGN5L0ZudzFsbWU0YTU2
        V3NoWkU0azE5eTNKeGIzTDYySlZ6cFUK+6Xe7dMdVevSzcuOHZ2zFq0z+GTIoS3I
        k5virbWoCdBGyyWhCcTfyovOvh/1G3PMT6KbvMKIFiXKDnAlwlQ1QA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T20:20:42Z"
  mac: ENC[AES256_GCM,data:9U0kI5wZCL38DY1a1BiSimx63dx85tsBkYtf7VVoLdv01hsbibNbOfi4pFt9L8O/UQ1BLGHQQKfCYkOdiUTecuuP7jQ1XL86sEnSbzI+v3/maGFivVoRZKOxcEvzJs5Alvbg2sLsO7LGhJQrgXVjeqvyr5Hh8iJ4tdnrptPY1l4=,iv:Vd0PjPX6nVVw2sExE+wgSveSXgEP1QnVABFaNLWs2TY=,tag:rZ9fIXaQAHLTu3XH4AHPJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
