apiVersion: v1
kind: Secret
metadata:
  name: todo-db-secret
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-db
    app.kubernetes.io/instance: todo-db
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:2VMzqoM=,iv:HNfmmnYax+9D20c3MMMYqFYptKOTTW8nGWSX4aCsiLY=,tag:YKRIWLMS1KkHh0UNCXn/5A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:26SQptEhr08=,iv:HjLy6uLXYifWoQoswoSJGEEtPKjVbgz9iQpFY9+g91M=,tag:nA71fAskEBtMFXWHNf4S6A==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:PvZiPeE=,iv:gjzUDK4uGnLlp6yBAHwxrJIcEEsc1IJOUxhys0aZ9dM=,tag:0Xu82uPjjiYRmAPwmooxNw==,type:str]
sops:
    age:
        - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOM0d2TkNSVkNqWWRrT2o3
            SnFzWXdwNzA0VUkyL1RRODIxQkhxMm0rRlFBCmJUL0RWQkxCVE0wOVByRWVHaDdi
            Z1lkRjdkUmF3b0x4TWtYOVRPMEZpOG8KLS0tIGZWNFBaNm1NWFRCMEhRMEVsbGdF
            REJBeGxyR2NyRWJnaS9kYThpUkhNdTgKSg21cj/a/oCC1L5idzae9OG0N3kLgPLR
            3ZrqDL56MS/hV8vq9zIg91RLv0Uke3Qs1si3f29sRcVArAALk3sz4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T20:08:49Z"
    mac: ENC[AES256_GCM,data:rRZvEl4j4OnUYWDXnoXjZQpbQ7Ieclsbl9qGnFZ1Ewn8kEGMPPv/WJlyfjRbPF2zf2mPnX0F9L6NXucO1x5aHnySQcqMG5cvvt0lLk6W0wNtXcc1AGDIYGargGJMrsb5MRSgKv/7Gu8+eQJxQoXi2AMjOMwvGJPs8+2dZScZoho=,iv:Y9QpRwv05qqc3kxoDWI7hQd0nXnBwq9M8DVBvsUfnos=,tag:adrI00ag2Nu1Xy3jyN8Ccg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
