apiVersion: v1
kind: Secret
metadata:
  name: todo-api-secret
  namespace: todo-app
  labels:
    app.kubernetes.io/name: todo-api
    app.kubernetes.io/instance: todo-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  DATABASE_URL: ENC[AES256_GCM,data:tKSY0mQkkqbh7AikXiTHOP0yKRf/xEHWI2qSEvdJsNCtzuYtAqyPTGtHDO9oT2Rpcgxf5j9H,iv:IONKs6cdOWuvjeZCl1EBz8e2Oi8JRUyMvKYZ0j4tM2M=,tag:rKuQ9o6SXPJBxQU/ykMUCw==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:VySlSXJ5oXUw46gu+QObWtszqOY5sg6cOrlGnJWNi0e6BR1YxgVH1/PlRpDlbsgPaI653Ad3yQMhobBqi1EaUw==,iv:RY+3fVkNkjfHtPyw6P4DL2n5EpGgfwlpuMxcaaugdOY=,tag:u1QuuaOx/v0y7OYJJhCMbw==,type:str]
sops:
  age:
    - recipient: age1fgv3cmqu3wr4akuvq33q7tjgjw8t8hzsqxwk4lds40vtjp02af2qyk330s
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMW04b3FTcnIwR3d3dVNM
        Zm9CVjBZampSWFpncFYzOURJYkQ5RGQrMlZnCmtnd1NNaDNpQW9JWGpIano3RnJh
        cFcyc0RVR0k0MklrWGdTVVNNaHlQZHMKLS0tIFF1ZlNyTDZ4MkJYaVRXT25TZTJ1
        UWVrci9uMkR5WU5HSDJzUlFwTjAyMGMKvTwkk2ZLClbSahlVuUO2MRNu2MxLX5k/
        YUEwmKItFdoePgg6JKMe8wSLudOUnCDpRMYvjUQMF4N6vWoyAlLzdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T18:46:23Z"
  mac: ENC[AES256_GCM,data:BpwApZ62o7Ex3uMjit+CTChlvs442ySh7trHrdVohgbw4OXOI3MVqkzdkzuRU7dmBbm+wWhZaG9addBHskMRgGl5OGbhWpZhtmICVr83PYFjF1DKbyaqzLFemLqOab7WEPk/OqintvFRkJC622C25oBTu+cTBU5lIGLA4Yo61VY=,iv:bfXvZ86IVytkWwtEVLld9BDlv7/RRvhHo7CxBeDZ72A=,tag:Fc5qASslXqSFTFORYNVl7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
