apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-app

resources:
  - namespace.yaml
  - network-policy.yaml
  - todo-api-serviceaccount.yaml
  - todo-api-configmap.yaml
  - todo-api-deployment.yaml
  - todo-api-service.yaml
  - todo-api-ingress.yaml
