apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-api-config
  labels:
    app.kubernetes.io/name: todo-api
    app.kubernetes.io/instance: todo-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
data:
  APP_NAME: "Todo API"
  DEBUG: "false"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  REFRESH_TOKEN_EXPIRE_DAYS: "7"
  OTEL_EXPORTER_OTLP_ENDPOINT: "alloy.monitoring.svc.cluster.local:4317"
  OTEL_SERVICE_NAME: "todo-api"
