apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-db
  labels:
    app.kubernetes.io/name: todo-db
    app.kubernetes.io/instance: todo-db
    app.kubernetes.io/version: "18"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
spec:
  serviceName: todo-db-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: todo-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: todo-db
        app.kubernetes.io/instance: todo-db
        app.kubernetes.io/version: "18"
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: todo-k8s
        app.kubernetes.io/managed-by: kustomize
    spec:
      containers:
        - name: postgres
          image: postgres:18-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          envFrom:
            - secretRef:
                name: todo-db-secret
          volumeMounts:
            - name: todo-db-data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "todo_admin", "-d", "todos"]
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "todo_admin", "-d", "todos"]
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
  volumeClaimTemplates:
    - metadata:
        name: todo-db-data
        labels:
          app.kubernetes.io/name: todo-db
          app.kubernetes.io/instance: todo-db
          app.kubernetes.io/component: database
          app.kubernetes.io/part-of: todo-k8s
          app.kubernetes.io/managed-by: kustomize
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
