apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnativepg
  labels:
    app.kubernetes.io/name: cloudnativepg
    app.kubernetes.io/instance: cloudnativepg
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
spec:
  project: default
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    targetRevision: "0.27.1"
    helm:
      releaseName: cloudnative-pg
      # TODO: increase replicaCount to 2 in a real multi-node production environment.
      values: |
        replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
