apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app-prod
  labels:
    app.kubernetes.io/name: todo-app-prod
    app.kubernetes.io/instance: todo-app-prod
    app.kubernetes.io/component: gitops
    app.kubernetes.io/part-of: todo-k8s
    app.kubernetes.io/managed-by: kustomize
spec:
  project: default
  source:
    repoURL: https://github.com/areebahmeddd/test-k8s
    targetRevision: prod
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
